### ISSUE TITLE
Building distributable for customization failing

### ISSUE THREAD

**Issue by jefp** [awslabs/iot-device-simulator#4]
Hi, 

I'm building a customized version of the simulator following the instructions of the README.
The process is failing throwing some errors about missing files and javascript exceptions:

```
Generating a manifest file ../dist/site-manifest.json for directory ../dist/console
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1156:14)
    at Object.<anonymous> **(X/deployment/manifest-generator/app.js:83:4)**
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup `(internal/bootstrap/node.js:285:19)
```
The deployment/manifest-generator/app.js:83 should have a callback function. 

https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

Also, the file deployment/iot-device-simulator.yaml is missing in the repo.

Best regards,
JF

**Comment by shsenior** [comment]
We will have a new version with some minor updates coming in the next few weeks. We will make sure this issue is addressed with the update.

**Comment by shsenior** [comment]
updated with v1.1.0
